<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>logistic</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Figgle" Version="0.6.6" />
    <PackageReference Include="Figgle.Fonts" Version="0.6.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="System.CommandLine" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductCentral.Core\ProductCentral.Core.csproj" />
    <ProjectReference Include="..\ProductCentral.Messaging\ProductCentral.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Binders\" />
  </ItemGroup>

</Project>
