<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>27c62535-d62a-4cfe-bdc4-f3e1f934acba</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductCentral.Core\ProductCentral.Core.csproj" />
    <ProjectReference Include="..\ProductCentral.RestClient\ProductCentral.RestClient.csproj" />
  </ItemGroup>

</Project>
